apiVersion: v1
entries:
  kubeview:
  - apiVersion: v2
    appVersion: 0.1.31
    created: "2022-10-08T21:24:13.721352177Z"
    description: Kubernetes cluster visualiser and visual explorer
    digest: 6e8d2761fef815b8bc86d887a5ca7f83ea27e1d9e57357e4742e3b717340453e
    home: https://github.com/benc-uk/kubeview
    icon: https://raw.githubusercontent.com/benc-uk/kubeview/master/web/client/public/favicon.png
    maintainers:
    - name: Ben Coleman
      url: https://benc.dev
    name: kubeview
    sources:
    - https://github.com/benc-uk/kubeview
    urls:
    - kubeview-0.1.31.tgz
    version: 0.1.31
  - apiVersion: v2
    appVersion: 0.1.30
    created: "2022-10-08T21:24:13.72081437Z"
    description: Kubernetes cluster visualiser and visual explorer
    digest: c62e04de16eee800090da637f0b4c1e7ed962d78f6563441db5b515df66da0e9
    home: https://github.com/benc-uk/kubeview
    icon: https://raw.githubusercontent.com/benc-uk/kubeview/master/web/client/public/favicon.png
    maintainers:
    - name: Ben Coleman
      url: https://benc.dev
    name: kubeview
    sources:
    - https://github.com/benc-uk/kubeview
    urls:
    - kubeview-0.1.30.tgz
    version: 0.1.30
  - apiVersion: v2
    appVersion: 0.1.20
    created: "2022-10-08T21:24:13.720279562Z"
    description: Kubernetes cluster visualiser and visual explorer
    digest: 8bcd7b6bacd57cf88d73117066aa7e492005bd0c02aa7f1f45b976edebd809a3
    home: https://github.com/benc-uk/kubeview
    icon: https://raw.githubusercontent.com/benc-uk/kubeview/master/web/client/public/favicon.png
    maintainers:
    - name: Ben Coleman
      url: https://benc.dev
    name: kubeview
    sources:
    - https://github.com/benc-uk/kubeview
    urls:
    - kubeview-0.1.20.tgz
    version: 0.1.20
  - apiVersion: v2
    appVersion: 0.1.19
    created: "2022-10-08T21:24:13.719737555Z"
    description: Kubernetes cluster visualiser and visual explorer
    digest: 6ad8a91705ea39f1f9acb35d9f2fd4fabd51ea02dfbe841636af27c3c4ae4d8e
    home: https://github.com/benc-uk/kubeview
    icon: https://raw.githubusercontent.com/benc-uk/kubeview/master/web/client/public/favicon.png
    maintainers:
    - name: Ben Coleman
      url: https://benc.dev
    name: kubeview
    sources:
    - https://github.com/benc-uk/kubeview
    urls:
    - kubeview-0.1.19.tgz
    version: 0.1.19
  - apiVersion: v2
    appVersion: 0.1.18
    created: "2022-10-08T21:24:13.719069046Z"
    description: Kubernetes cluster visualiser and visual explorer
    digest: f6f278b6df544c1d5f97327fef9801a9bb4743ccafeea956bdaa6a9011038651
    home: https://github.com/benc-uk/kubeview
    icon: https://raw.githubusercontent.com/benc-uk/kubeview/master/web/client/public/favicon.png
    maintainers:
    - name: Ben Coleman
      url: https://benc.dev
    name: kubeview
    sources:
    - https://github.com/benc-uk/kubeview
    urls:
    - kubeview-0.1.18.tgz
    version: 0.1.18
  - apiVersion: v2
    appVersion: 0.1.17
    created: "2022-10-08T21:24:13.718433137Z"
    description: Kubernetes cluster visualiser and visual explorer
    digest: c4fb7f57615497039606feefaa3b5dd0ae53bc0c2383bb4209b55bff5f1d6800
    home: https://github.com/benc-uk/kubeview
    icon: https://raw.githubusercontent.com/benc-uk/kubeview/master/web/client/public/favicon.png
    maintainers:
    - name: Ben Coleman
      url: https://benc.dev
    name: kubeview
    sources:
    - https://github.com/benc-uk/kubeview
    urls:
    - kubeview-0.1.17.tgz
    version: 0.1.17
generated: "2022-10-08T21:24:13.717628927Z"
